print "print string1 use print, "
puts "print string1 use puts"
print "print string2 use print, "
puts "print string2 use puts"
print "print string3 use print, "
puts "print string3 use puts"
print "print string4 use print, "
puts "print string4 use puts"
print "print string5 use print, "
puts "print string5 use puts"
print "print string6 use print, "
puts "print string6 use puts"
print "print string7 use print, "
puts "print string7 use puts"